### PR TITLE
fix(importCDX): Remove view BY_VCS_LOWERCASE and BY_PURL_LOWERCASE

### LINKED ISSUE #2170: Code changes are required in the PR-2154.
### Description
After a re-examining the PR - #2154 some changes are needed.

In,

1. ComponentRepository.java file: BY_VCS_LOWERCASE view should be removed.
2. PackageRepository.java: BY_PURL_LOWERCASE view should be removed.

### PR DESCRIPTION
**Pull request by sameed20**
Description: 
Two non-functioning view BY_VCS_LOWERCASE and BY_PURL_LOWERCASE has been removed.

Issue:  Closes #2170

### CODE REVIEW

**Comment by KoukiHama** [comment]
GitHub action returned Error.

**Review by afsahsyeda — APPROVED** [review]

**Comment by afsahsyeda** [comment]
Code Looks good to me.

**Comment by akshitjoshii** [comment]
Hi @sameed20, SW360 Docs link at the footer is not working.
Capture1

**Comment by sameed20** [comment]
> Hi @sameed20, SW360 Docs link at the footer is not working. Capture1

@akshitjoshii I pulled the latest main, and tried opening SW360 Docs link in that, it's not opening in the main as well. I think this need to be fixed by creating a separate issue.

**Comment by KoukiHama** [comment]
I see. I  make new issue for doc page.

**Comment by akshitjoshii** [comment]
Apart from doc page issue, It is working as expected.

**Pull request merged**
