### PR TITLE
feat(rest) Specify properties dynamically in GET /releases

### PR DESCRIPTION
**Pull request by blaumeiser-at-bosch**
Signed-off-by: Henrik Engelbrink <henrik.engelbrink@bosch-si.com>

### CODE REVIEW

**Comment by hengel2810** [comment]
This pull-request implements the functionality to define a `fields` parameter in the GET .../releases request. All properties in this `fields` parameter are returned for the releases in the response if they have these properties. This allows a more dynamic use of this route for clients using this API. 


Request: GET .../resources/api/releases?fields=releaseDate,cpeid

Response:
```
{
    "_embedded": {
        "sw360:releases": [
            {
                "name": "Release 1",
                "releaseDate": "28-07-2018",
                "cpeid": "Xahd72jd9",
                "_links": {
                    "self": {
                        "href": "http://localhost:8080/resource/api/releases/0ab383d191df0e69bb6a2c69e700096a"
                    }
                }
            }
        ]
    },
    "_links": {
        "curies": [
            {
                "href": "http://localhost:8080/resource/docs/html5/{rel}.html",
                "name": "sw360",
                "templated": true
            }
        ]
    }
}
```

**Comment by hengel2810** [comment]
PR is rebased

**Comment by maierthomas** [comment]
@hengel2810 please update also the releases.adoc file

A `GET` request will list all of the service's components. The `fields` parameter defines which component object properties should be contained in the response.

```
[[resources-releases-list-with-fields]]
==== Listing releases with fields
..........
```

**Comment by maierthomas** [comment]
tested successfully!

image

**Comment by hengel2810** [comment]
@maierthomas: I've updated the **releases.adoc**

**Pull request merged**
