### PR TITLE
chore(release): tag release 19.1.0

### PR DESCRIPTION
**Pull request by GMishx**
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

Proposing release 19.1.0 with multiple features and vulnerability fixes.

### CODE REVIEW

**Comment by GMishx** [comment]
@KoukiHama @tuannn2 @heliocastro @smrutis1 can we go ahead and merge this branch to tag the release?

**Review by smrutis1 — DISMISSED** [review]
Good to go from myside.

**Review by heliocastro — APPROVED** [review]
First minor good to go

**Comment by GMishx** [comment]
Rebased with latest main. Please approve and merge. I will create the tag and release.

**Review by KoukiHama — APPROVED** [review]

**Comment by KoukiHama** [comment]
LGTM

**Pull request merged**
