### PR TITLE
fix(package): Create package by API can't link release

### PR DESCRIPTION
**Pull request by tuannn2**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### How To Test?

- Execute API create new Package: 
```
$ curl 'https://sw360.org/api/packages' -i -X POST \
    -H 'Content-Type: application/hal+json' \
    -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5NzQ0MzY4OSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6IlhKQVFFQkZyeGxieFJONUFRSDU3dGtfYzJkbyIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.ZueR84mNgqUULCYXTkFSSX4GGb01nPFcrINisAE5x8DCjdH1SQp7TeHoLmBi75QPzSBTlMCf66_1G3CVU7w_AqCV9aohl2OFELEQRHKbdI3KcRHWEBd-cW5SuLs-zcb8AmSDVju7uCEuoCluq35BgfvVI-YtlboGWkuZBW_jRSuSnFn4S0M2UyrE4g0VR-a7xmYE2TLvGW9IwWrev0vVCdDTslkXkyU098ze9JwOlLJvco5OxHNJQ4c0sozdz49iQNq1-qERu111A0pxt5AzCnr4cCsEvhO9Js_PVVpMUgTEMsRz5Yy03CgLfA9rD8t2L6azXqtKDWHftBkajMlMnA' \
    -d '{
  "name" : "angular-sanitize",
  "version" : "1.8.2",
  "packageType" : "LIBRARY",
  "purl" : "pkg:npm/angular-sanitize@1.8.2",
  "vcs" : "git+https://github.com/angular/angular.js.git",
  "homepageUrl" : "https://github.com/angular/angular-sanitize",
  "licenseIds" : [ "GPL", "MIT" ],
  "releaseId" : "98745",
  "description" : "Sanitizes a html string by stripping all potentially dangerous tokens."
}'
```

- Expected response:

```
{
  "name" : "angular-sanitize",
  "version" : "1.8.2",
  "purl" : "pkg:npm/angular-sanitize@1.8.2",
  "packageType" : "FRAMEWORK",
  "releaseId" : "98745",
  "licenseIds" : [ "GPL", "MIT" ],
  "description" : "Sanitizes an html string by stripping all potentially dangerous tokens.",
  "homepageUrl" : "http://angularjs.org",
  "vcs" : "git+https://github.com/angular/angular.js.git",
  "_links" : {
    "self" : {
      "href" : "https://sw360.org/api/packages/122357345"
    }
  },
  "_embedded" : {
    "sw360:release" : {
      "name" : "Test Release",
      "version" : "2",
      "_links" : {
        "self" : {
          "href" : "https://sw360.org/api/releases/98745"
        }
      }
    },
    "createdBy" : {
      "email" : "admin@sw360.org",
      "deactivated" : false,
      "_links" : {
        "self" : {
          "href" : "https://sw360.org/api/users/byid/123456789"
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by nikkuma7** [comment]
Hi @KoukiHama ,
Two fields are not coming in response : 
1: createdOn
2: packageManager
Even though both fields are there in the Database.

image
image

**Comment by KoukiHama** [comment]
@tuannn2 could you check it?

**Comment by tuannn2** [comment]
Hi @nikkuma7, 
This PR only focus to issues Package link to Release. It does not affect the response of the API Create Package.
According to the original specification, the above 2 properties are not returned in response.

I think we should keep the API's current response as is.

**Comment by KoukiHama** [comment]
@afsahsyeda Could you tell us what do you think this?

**Comment by afsahsyeda** [comment]
Hi @KoukiHama, I didn't include the "package manager" field in the previous response as it is already evident from the "purl" field. Additionally, the "createdOn" field is only generated when requesting "allDetails" of a package. I believe a similar response structure is maintained for projects, components, and other entities.

**Comment by KoukiHama** [comment]
For this PR, We can ignore these items.
1: createdOn
2: packageManager

However, lets make new issue for the response about  createdOn , after merge this PR.

**Comment by nikkuma7** [comment]
As per the above comment, Test successful.

**Comment by KoukiHama** [comment]
codes are good.

**Pull request merged**
