### PR TITLE
fix(rest) : attachment usage type fix in response

### LINKED ISSUE #2318: Return value of field attachmentType in endpoint '/projects/{id}/attachmentUsage' in incorrect format.
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Return value of field attachmentType in endpoint '/projects/{id}/attachmentUsage' in incorrect format.

image

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

### PR DESCRIPTION
**Pull request by keerthi-bl**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: 
Closes #2318 

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Too many fields are getting returned.

image

(highlighted fields not required)

**Comment by keerthi-bl** [comment]
Changes pushed @rudra-superrr

**Comment by rudra-superrr** [comment]
oblComp_4(1) release has 3 attachments and your response is showing only 1 as you converted list of attachment to map.

image

image

**Comment by rudra-superrr** [comment]
Testing was successful.

**Comment by rudra-superrr** [comment]
duplicate attachments for some releases.

image

**Comment by rudra-superrr** [comment]
Release Id not getting shown in release link.
image

**Comment by rudra-superrr** [comment]
Testing was successful.

**Comment by rudra-superrr** [comment]
LGTM

**Pull request merged**
