### PR TITLE
feat(obligation): list license obligation table data 

### LINKED ISSUE #2301: List license obligation table's data of a project
### Description

Need new endpoint to list the license obligation data of a project.

### PR DESCRIPTION
**Pull request by rudra-superrr**
Issue: Closes #2301 

Description: 
This new endpoint will list license obligation data for the given project.

### CODE REVIEW

**Comment by eldrin30** [comment]
Test succesful
Screenshot from 2024-02-12 11-50-03

**Comment by rudra-superrr** [comment]
Review comments addressed.

**Comment by hoangnt2** [comment]
Code look good to me

**Comment by ag4ums** [comment]
This PR is dependent on #2276, merge this after merging #2276

**Pull request merged**
