### PR TITLE
feat(license): Create new api update license

### PR DESCRIPTION
**Pull request by tuannn2**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### How To Test?

- Run command line: 
```
$ curl 'https://sw360.org/api/licenses/Apache-2.0' -i -X PATCH \
    -H 'Content-Type: application/hal+json' \
    -H 'Authorization: BearereyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5OTQxOTQ0OSwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6ImlyaWwxUDF5Rm1uY2kzaThyNlROWFZJemVvTSIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.ggC1M326qKTL6WZhGX-oW-Ti8DGYGNO31g10mFxmgoiT9tIYvZOFnalGBECD5ZcmfHwoFx4_FwU6mjHMgd2FKcsvwRAVKryXOLIWkmno5IVPcHFNuSfMiqVSBQ5Hnl2HrpfGDr1tBmd5Mzg3SeffrPSvZnZNrqKDZmiCbWgx-RYL4PF6UDLk9pXOkfcQLrgjASBF7n4ulcK1z9Na12HFBHDPSheLFZa2sTty9TMt2yREgDlJZXx-Vh-F0YeRW66nau99TI3KqCqYtzoGRhqphVloMgg54-OlX0cyt7F9l3sQ0bo9HW7rkMve8TRlvIr266k4AePE2XMVxapCS-qgIw' \
    -H 'Accept: application/hal+json' \
    -d '{
  "note" : "Apache License",
  "fullName" : "Apache License 4.0"
}'

```

- Response:

```
{
  "externalLicenseLink" : "https://spdx.org/licenses/Apache-2.0.html",
  "note" : "Apache License",
  "externalIds" : {
    "Trove" : "License :: OSI Approved :: Apache Software License",
    "SPDX" : "Apache-2.0"
  },
  "additionalData" : {
    "Key" : "Value"
  },
  "OSIApproved" : "NA",
  "FSFLibre" : "NA",
  "text" : "placeholder for the Apache 2.0 license text",
  "checked" : true,
  "shortName" : "Apache 2.0",
  "fullName" : "Apache License 4.0",
  "_links" : {
    "self" : {
      "href" : "https://sw360.org/api/licenses/Apache-2.0"
    }
  }
}

```

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by keerthi-bl** [comment]
Testing was successful.

image


image

**Comment by heliocastro** [comment]
@tuannn2  I hope the credential you pasted above are intentional and aren't valid in any essential open system

**Review by heliocastro — COMMENTED** [review]
What about the License text ?

**Comment by tuannn2** [comment]
> @tuannn2 I hope the credential you pasted above are intentional and aren't valid in any essential open system

Yes. It's no problem. it's just an example.

> What about the License text ?

I only give an example of 2 fields in How to test, but the license text and license fields can be edited normally.

**Review by smrutis1 — APPROVED** [review]
Code looks good

**Pull request merged**
