### PR TITLE
feat(clearing): Improved cloud backend clearing

### PR DESCRIPTION
**Pull request by smrutis1**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

* Added clearing process for cloud backend. 

> * Which issue is this pull request belonging to and how is it solving it? (*#1922*)
> * Did you add or update any new dependencies that are required for your change? - No

Issue: 

Please refer the issue #1922 

> Have you implemented any additional tests? - No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by GMishx** [comment]
Testing results:
- [x] New attachment type exists
    image
- [x] New Clearing state updated
    image
- [ ] Clearing state at project level is not updated
    image
    image

Is it an expected behavior @smrutis1 ?

**Comment by smrutis1** [comment]
> * [ ]  Clearing state at project level is not updated
>   image
>   image
> 
> Is it an expected behavior @smrutis1 ?

@GMishx This is expected as this clearing state is related to project not the release.

**Comment by GMishx** [comment]
Thanks for confirming @smrutis1 .

Adding clearing report to the release also changes the Clearing state to Report Available (blue) and accepting it makes CS to Report approved.

**Review by GMishx — APPROVED** [review]
Changes looks good.

Tested, working as expected.

**Pull request merged**
