### PR TITLE
Feat(User): Create new endpoints to Create/Revoke/List rest API token for users

### PR DESCRIPTION
**Pull request by hoangnt2**
### What does this PR do?:
1. Create endpoint to list all user's tokens.
2. Create endpoint to create new user's token.
3. Create endpoint to revoke user's token by its name.

### How To Test?
**1. Endpoint to list all user's tokens**

#### Procedure:
- Send GET request to http://localhost:8080/resource/api/users/tokens
#### Expected:
- Response will list all Rest API token of the requesting user. (Status code 200).

**2. Endpoint to create new user's token**

#### Procedure:
- Send POST request to http://localhost:8080/resource/api/users/tokens with request body:

```
{
  "name" : "MyToken3",
  "expirationDate" : "2023-12-29",
  "authorities" : ["READ", "WRITE"]
}
```

#### Expected:
- Response will contain created token. (Status code 201).
- A new Rest API token will be created for requesting user.
- You can use this created token to authenticate API request by setting Authorization header in this format: **Token {created_token}**

**3. Endpoint to revoke user's token by name**

#### Procedure:
- Send DELETE request to http://localhost:8080/resource/api/users/tokens?name={token_name}:

#### Expected:
- Token will be revoked from requesting user.

Refer to user Rest API doc (http://localhost:8080/resource/docs/api-guide.html#resources-users) for more information.

### CODE REVIEW

**Comment by keerthi-bl** [comment]
Testing this PR

**Comment by keerthi-bl** [comment]
Test successful.

s1_1

s1_2

s1_3

**Comment by rudra-superrr** [comment]
Hi @hoangnt2 , can you please resolve the merge conflicts.

**Comment by hoangnt2** [comment]
> Hi @hoangnt2 , can you please resolve the merge conflicts.

The conflict has been resolved

**Comment by rudra-superrr** [comment]
LGTM

**Pull request merged**
