### PR TITLE
feat(rest): new endpoint listing component attachments

### PR DESCRIPTION
**Pull request by muhammadali9699**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * This endpoint will list down all the attachments of single component.

Issue: #2016

### CODE REVIEW

**Comment by tuannn2** [comment]
Hi @muhammadali9699
We already have an endpoint for Listing component attachments.

duplicateListingAttachement

**Comment by nikkuma7** [comment]
Test successful.
image
image

**Comment by KoukiHama** [comment]
According to @tuannn2 ,
we already have endpoint for Listing component attachments.

How different this PR from exist one?
@ag4ums

**Comment by muhammadali9699** [comment]
Actually I couldn't find this endpoint in documentation when I created this issue and PR was also not mentioned in this new UI endpoints list https://github.com/eclipse-sw360/sw360-frontend/issues/10 so because of this misunderstanding it got redundant and I think we have to delete this PR. Sorry for inconvenience.

**Comment by ag4ums** [comment]
Closing the PR as the endpoint already exist.

**Pull request closed without merging**
