### PR TITLE
Version normalization

### PR DESCRIPTION
**Pull request by heliocastro**
Cleanup versions due report in issue #1808

### CODE REVIEW

**Comment by ljaenicke** [comment]
I have tested the branch. It looks much better now... but I still am seeing issues.
To reproduce: build everything from scratch (all containers pruned, volumes removed, ...). The server now starts up fine. I can set up the initial system following https://www.eclipse.org/sw360/docs/deployment/legacy/deploy-liferay7.4/.
The first step now is to load the SPDX license information (Still using the setup@sw360.org account, Admin->License->Import SPDX Information). This operation fails:
Screenshot 2023-04-20 084826
In the log, the information
  ERROR [UserCacheHolder:76] Unable to fetch user...
can be found.
[transcript.gz](https://github.com/eclipse-sw360/sw360/files/11283409/transcript.gz)

**Comment by ljaenicke** [comment]
Note: I when testing yesterday with the slim-war mechanism disabled, I was able to successfully import the SPDX information, so I do not think this might be related to Issue #1810.

**Comment by heliocastro** [comment]
@KoukiHama We still have all the old and new spdx libraries as dependencies. Can you check what are valid ?

**Comment by heliocastro** [comment]
@ljaenicke Btw, this is the experimental test branch, will not be committed this way. I commited a single ont for remove couchdb_lucene from slim_jars now

**Pull request closed without merging**
