### PR TITLE
fix(rest): Added code for updating multiple project attachments.

### PR DESCRIPTION
**Pull request by nikkuma7**
Closes : #2491 

### Description
Recently, we were able to upload a single file as an attachment, but after these code changes, we can now upload multiple files, including the same file or modified versions.

http://localhost:8080/resource/api/projects/{projectId}/attachments

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Not working as expected.
image

and please update the rest doc properly for this endpoint as both the parameter of the body is taking file type. The attachment paramter should be taking attachment required information.

**Comment by rudra-superrr** [comment]
The current endpoint returns the whole project in response and yours give is empty.
image

**Comment by rudra-superrr** [comment]
On uploading multiple files, all files having same attachment information. User should be able to change the attachment information(type, status, comment) with respect to each file.
image

**Comment by rudra-superrr** [comment]
Please display some message if same file is uploaded again.

**Comment by rudra-superrr** [comment]
image
image

Since this endpoint can upload multiple attachments so we don't need attachment key in your curl command.
Also limit the attachment info (filename, checkStatus, createdComment and attachmentType are enough).

**Comment by rudra-superrr** [comment]
image

Please display some message if same file is uploaded again, right now its giving internal server error.

**Comment by nikkuma7** [comment]
@rudra-superrr Addressed comment.

**Comment by rudra-superrr** [comment]
Testing was successful.
image

image

**Review by GMishx — APPROVED** [review]
LGTM

**Pull request merged**
