### PR TITLE
feat(CreateCRandRequestsPortlet):Added new field Clearing Type for CR and Additional columns in Open CR table

### LINKED ISSUE #2139: New field- Clearing type High(ISR) and Deep(CLX) for Clearing Requests
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Add checkboxes in the Create CR dialog where Deep would be checked by default. This can be edited after the CR is created.
- [x] Deep (CLX)
- [ ] High Level  (ISR)

### LINKED ISSUE #2141: Open CR's table changes
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

1. Include Date columns in Open CR table for clarity (avoid opening each CR for Dates). Currently, these columns are only available in the Closed CR table.

image

2. Column to include the Clearing Type: High or Deep
3. Remove progress bar for the Clearing Progress column and indicate only the percentage number to save table space.

### PR DESCRIPTION
**Pull request by afsahsyeda**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

**Description**
- Clearing Type field with values HIGH and DEEP has been added to Clearing Request.
- High level clearing for ISR and Deep level clearing CLX. It is a mandatory field while creating a CR.
image

- Created On, Preferred Clearing Date, Agreed Clearing Date and Clearing Type columns have been added to Open CR table.
image
 
Closes #2141 
Closes #2139

### CODE REVIEW

**Comment by akshitjoshii** [comment]
Working fine as of now, An information(i) button can be added while the CR is being created by the user so that the user knows what clearing type means.
2023-10-12 14_15_52-SW360_NEW  Running  - Oracle VM VirtualBox

**Comment by akshitjoshii** [comment]
**i** button working fine while creating the Cleating Request but while viewing the created request the **i** button info is overlapping with the "clearing request comments" bar below hiding some part of the information.
Capture2

**Comment by afsahsyeda** [comment]
> **i** button working fine while creating the Clearing Request but while viewing the created request the **i** button info is overlapping with the "clearing request comments" bar below hiding some part of the information. Capture2

Hi @akshitjoshii , this should be fine because the info text is not visible until we hover over the clearing type field. The indentation of the lines in info dialog cannot be changed as it would affect its visibility in the open CR table.

**Comment by sameed20** [comment]
Please add the keys and values in the in Language.zh file as well.

**Comment by afsahsyeda** [comment]
> Please add the keys and values in the in Language.zh file as well.

@sameed20 you can check now

**Comment by sameed20** [comment]
> > Please add the keys and values in the in Language.zh file as well.
> 
> @sameed20 you can check now

Code looks good,

**Review by smrutis1 — APPROVED** [review]
Code looks good

**Pull request merged**
