### PR TITLE
feat(Project): Create new endpoint to serve list view of dependency network (New GUI)

### PR DESCRIPTION
**Pull request by hoangnt2**
### Pre-condition:
Turn on feature by adding this property into /etc/sw360/sw360.properties: **enable.flexible.project.release.relationship=true**

### How To Test?
Step 1: Create a new project with dependency network:
- Url: http://localhost:8080/resource/api/projects/network
- Method: POST
- Body: 
```
{
    "name": "Test_PR",
    "dependencyNetwork": [
        {
            "releaseId": "${release_id_1_in_sw360}", // Replace this by an existing release id in sw360
            "releaseRelationship": "CONTAINED",
            "mainlineState": "OPEN",
            "comment": "",
            "createOn": "2024-07-05",
            "createBy": "admin@sw360.org",
            "releaseLink": [
                {
                    "releaseId": "${release_id_2_in_sw360}", // Replace this by an existing release id in sw360 (difference from above)
                    "releaseRelationship": "OPTIONAL",
                    "mainlineState": "MAINLINE",
                    "comment": "",
                    "createOn": "2024-07-05",
                    "createBy": "admin@sw360.org",
                    "releaseLink": []
                }
            ]
        }
    ]
}
```

Step 2: Test get list view of dependency network:
- Url: http://localhost:8080/resource/api/projects/network/${created_project_id_at_step_1}/listView
- Method: GET
- Expected output: The response body will be shown as below:

```
[
    {
        "isAccessible": "true",
        "clearingState": "New",
        "mainLicenses": "",
        "type": "Service",
        "projectMainlineState": "Open",
        "relation": "Contained",
        "isRelease": "true",
        "releaseMainlineState": "Open",
        "projectOrigin": "${Project_name}",
        "name": "${release_name_2}",
        "releaseOrigin": "",
        "comment": "",
        "id": "${release_id_1}"
    },
    {
        "isAccessible": "true",
        "clearingState": "New",
        "mainLicenses": "",
        "type": "OSS",
        "projectMainlineState": "Mainline",
        "relation": "Optional",
        "isRelease": "true",
        "releaseMainlineState": "Open",
        "projectOrigin": "${Project_name}",
        "name": "${release_name_2}",
        "releaseOrigin": "${release_name_1}",
        "comment": "",
        "id": "${release_id_2}"
    }
]
```

### CODE REVIEW

**Comment by hoangnt2** [comment]
This is back-end of this PR https://github.com/eclipse-sw360/sw360-frontend/pull/289

**Comment by akshitjoshii** [comment]
Testing this PR.

**Comment by akshitjoshii** [comment]
Test was successful.
Url: http://localhost:8080/resource/api/projects/network
image



Url: http://localhost:8080/resource/api/projects/network/${created_project_id_at_step_1}/listView
image

**Comment by hoangnt2** [comment]
@akshitjoshii Thank you

**Comment by akshitjoshii** [comment]
Hi @hoangnt2 , adding this property in sw360.properties file :  **enable.flexible.project.release.relationship=true** is causing an issue while building with TCs. With this property added, the build is failing with the error as mentioned below for regardless of the branch we are on. Can you pls check? Similar issue faced by @sameed20 with #2614 

image

**Comment by hoangnt2** [comment]
> Hi @hoangnt2 , adding this property in sw360.properties file : **enable.flexible.project.release.relationship=true** is causing an issue while building with TCs. With this property added, the build is failing with the error as mentioned below for regardless of the branch we are on. Can you pls check? Similar issue faced by @sameed20 with #2614
> 
> image

It look like 

> Hi @hoangnt2 , adding this property in sw360.properties file : **enable.flexible.project.release.relationship=true** is causing an issue while building with TCs. With this property added, the build is failing with the error as mentioned below for regardless of the branch we are on. Can you pls check? Similar issue faced by @sameed20 with #2614
> 
> image

I will check it, thanks for your information

**Comment by hoangnt2** [comment]
@akshitjoshii I have fixed above error in this PR https://github.com/eclipse-sw360/sw360/pull/2636. Thanks a lot

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Pull request merged**
