### PR TITLE
Fix bug: Project test fail when enable.flexible.project.release.relationship=true

### PR DESCRIPTION
**Pull request by hoangnt2**
Fix bug: Project test fail with enable.flexible.project.release.relationship=true
Ref: https://github.com/eclipse-sw360/sw360/pull/2612#issuecomment-2404432363

### CODE REVIEW

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by GMishx** [comment]
@akshitjoshii or @sameed20 can you please help with the test?

**Comment by akshitjoshii** [comment]
Test was successful. 

**Before fix** : 

before_fix


**After fix** : 


after_fix

**Review by heliocastro — APPROVED** [review]
LGTM

**Pull request merged**
