### PR TITLE
feat(rest): includeAllAttachments parameter in licenseInfo endpoint

### PR DESCRIPTION
**Pull request by afsahsyeda**
### Description

The parameter "**includeAllAttachments**" when set to true generates license info file for a project including both CLX and ISR attachment of a release (only one attachment per release is considered and CLX is preferred).

#### How to reproduce

Query the GET endpoint for licenseInfo of a project.

#### Screenshots ( if applicable )

image

### CODE REVIEW

**Comment by GMishx** [comment]
@afsahsyeda please rebase with latest main to get the REST test cases.

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by afsahsyeda** [comment]
This feature has been tested and is live on our production environment,

**Comment by afsahsyeda** [comment]
This feature is live in our production environment and is working fine.

**Pull request merged**
