### PR TITLE
feat(rest): modify moderation requests

### PR DESCRIPTION
**Pull request by GMishx**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

The PR adds new HTTP verbs to endpoint `/moderationrequest` to modify ModerationRequests from REST API.

* Which issue is this pull request belonging to and how is it solving it?
> PR is related to issue #1849
* Did you add or update any new dependencies that are required for your change?
> No

Issue: #1849

Create several moderation requests to perform following actions on the endpoint.
- `PATCH` `/moderationrequest/{id}`
  - With `action` as `ACCEPT` in body and some `comment`, the request should accept the MR.
- `PATCH` `/moderationrequest/{id}`
  - With `action` as `REJECT` in body and some `comment`, the request should reject the MR.
- `PATCH` `/moderationrequest/{id}`
  - With `action` as `ASSIGN` in body, the request should assign the MR to the caller and set the status to "in progress".
- `PATCH` `/moderationrequest/{id}`
  - With `action` as `ASSIGN` in body, for a MR where caller is not a moderator should throw error.
- `PATCH` `/moderationrequest/{id}`
  - With `action` as `UNASSIGN` in body, the request should remove the caller from the moderator list of the MR and set the status to "pending".
- `PATCH` `/moderationrequest/{id}`
  - With `action` as `UNASSIGN` in body, for a MR with only one moderator should throw error.

> Have you implemented any additional tests?

REST documentation tests.

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Things that I found while testing,
1. Getting message "You are the last moderator for this request - you are not allowed to unsubscribe" even if the reviewer is not a moderator.
2. Un assigning a user from a moderator list gives 202 status code i.e. it is removed from the mod list but if we run the same unassign api call then it will again give 202 status code.

**Comment by rudra-superrr** [comment]
500 status code coming when accept or reject operation is performed for a user which is not a moderator.
image

**Comment by GMishx** [comment]
Added an exception handler for the same @rudra-superrr . Also, blocked all calls to closed MRs.

Please have a look

**Comment by rudra-superrr** [comment]
Testing was successful.

**Comment by rudra-superrr** [comment]
Code looks good.

**Pull request merged**
