### PR TITLE
feat(rest) : Add enableSvm field in response to projects api

### PR DESCRIPTION
**Pull request by keerthi-bl**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #2157 

Sample URL : 

image

Sample response : 

image

> Have you implemented any additional tests?
No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by nikkuma7** [comment]
Data not coming showing under project,when i pass luceneSearch=true as a request parameter.

image

data coming for luceneSearch=false and name={projectName}

image

**Comment by keerthi-bl** [comment]
@nikkuma7 as discussed, please do the local setup for lucenesearch and try.. it should work. FYR, attaching screenshot..

image

**Comment by nikkuma7** [comment]
Test successful.

image

**Comment by nikkuma7** [comment]
Test successful.

image

**Review by ag4ums — APPROVED** [review]
Chnages looks good

**Pull request merged**
