### PR TITLE
fix(rest): fix test rest api of component

### PR DESCRIPTION
**Pull request by tuannn2**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue:  #2026

### How To Test?
Command line to Build: 
```
mvn clean package -P deploy -Dbase.deploy.dir=. -Dliferay.deploy.dir=${LIFERAY_INSTALL}/deploy -Dbackend.deploy.dir=${LIFERAY_INSTALL}/tomcat-9.0.56/webapps -Drest.deploy.dir=${LIFERAY_INSTALL}/tomcat-9.0.56/webapps -Dtest=org/eclipse/sw360/rest/resourceserver/restdocs/* -Dhelp-docs=true -Dsurefire.failIfNoSpecifiedTests=false
``` 
Result: 
SuccessLocal

### CODE REVIEW

**Review by ag4ums — APPROVED** [review]
Changes looks good

**Comment by ag4ums** [comment]
But the home page is distorted and also after login the portlets are not loaded

**Comment by KoukiHama** [comment]
> But the home page is distorted and also after login the portlets are not loaded
This PR seems to be just adding 1 line test codes. Is this issue related to the change?
How about latet main branch?  Can latest one load home page correctly?

**Comment by KoukiHama** [comment]
OK. Thank you.
I will check home page issue tomorrow.

**Comment by ag4ums** [comment]
Now it worked fine not sure may be a installation issue..

**Pull request merged**
