### PR TITLE
chore(release): 19.0.0-SNAPSHOT version

### PR DESCRIPTION
**Pull request by GMishx**
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

First version tag after 19.0.0 release.

### Suggest Reviewer
@heliocastro @KoukiHama @ag4ums @arunazhakesan

### How To Test?
Build and install SW360.

### CODE REVIEW

**Review by heliocastro — COMMENTED** [review]
Should we use SNAPSHOT or 19.99.x ?

**Comment by GMishx** [comment]
19.99.x will not be helpful if we want to follow semantic versioning.

I created this SNAPSHOT branch following previous releases. I am not sure about Maven versioning scheme yet. What would be the best way to do this?

**Comment by GMishx** [comment]
I read about Maven versioning and understood `SNAPSHOT` versions force maven to pull latest artifact from maven repository. Since we are not publishing anything there, we can skip the `SNAPSHOT` version and just follow the semantic versioning.

**Comment by heliocastro** [comment]
@GMishx Maybe close this PR and push 19.0.1 instead ?
You can use this:
```
mvn versions:set -DnewVersion=19.0.1
```

**Comment by GMishx** [comment]
Closing the PR as proposed. Will update the release document and open new PR for 19.0.1

**Pull request closed without merging**
