### PR TITLE
feat(liferay): Export private pages include package portlet

### PR DESCRIPTION
**Pull request by tuannn2**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #2068

### Suggest Reviewer
@KoukiHama @ag4ums

### How To Test?
For user who use the package feature.
Import lar file in: `sw360/frontend/configuration/Private_Pages_7_4_3_18_GA18_with_package_portlet.lar `

ImportLArFile

### Result:

ExpectedPackagePortlet

### CODE REVIEW

**Comment by KoukiHama** [comment]
Package portlets are a configurable feature, so conventional Lar files should also remain

**Comment by KoukiHama** [comment]
Keep : Private_Pages_7_4_3_18_GA18.lar  for user who dont use package features
Add:  Private_Pages_7_4_3_18_GA18_with_package_portlet.lar  for user who use the package feature.

So, we should have 2 types 7.4.3 private lar files. Not replacing, but adding new18_GA18_with_package_portlet.lar

**Comment by tuannn2** [comment]
Thanks for your comment, @KoukiHama
I updated.

**Comment by KoukiHama** [comment]
image

lar file is ok. And its lar show package portlet.

**Comment by heliocastro** [comment]
Humm, we should replace the main one. I really don't like to have two lar files around

**Pull request merged**
