### PR TITLE
feat(REST): Add restricted project counter for component and release usedBy API

### PR DESCRIPTION
**Pull request by hoangnt2**
### How To Test?
- Send GET request to
    + http://localhost:8080/resource/api/components/usedBy/{componentId}
    + http://localhost:8080/resource/api/releases/usedBy/{releaseId}

- Expected:
   + The response will contain number of restricted projects (of current user) :
    ```
      "sw360:restrictedResources" : [ {
            "projects" : {number_of_restricted_projects}
       } ]
    ```

### CODE REVIEW

**Comment by nikkuma7** [comment]
image
In above SS two projects has restricted.
image
Project restricted count is showing 0 while trigger from the postman (rest api ).
Rest response is not matching as per the UI.

**Comment by hoangnt2** [comment]
@nikkuma7, are you using the same account for authentication?

**Comment by nikkuma7** [comment]
> @nikkuma7, are you using the same account for authentication (GUI and RestAPI)?

Yes, use the same account  (Test admin ).

**Comment by hoangnt2** [comment]
> Yes, use the same account (Test admin ).

@nikkuma7 Ok, I got it. Let me check it.

**Comment by hoangnt2** [comment]
@nikkuma7, the API work properly on my side. Could you describe your steps to reproduce it?
image
image

**Comment by nikkuma7** [comment]
Test was successful.
image
image

**Comment by hoangnt2** [comment]
> Test was successful. image image

@nikkuma7 Thanks for trying again

**Review by smrutis1 — APPROVED** [review]
CLGTM

**Pull request merged**
