### PR TITLE
chore(rel-18.1): changing files for tagging 18.1

### PR DESCRIPTION
**Pull request by ag4ums**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
release 18.1.0

Issue: 

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Review by KoukiHama — APPROVED** [review]

**Comment by KoukiHama** [comment]
@tienlee  Could you also check it?

**Comment by KoukiHama** [comment]
Sorry, I have forgot these issue.
#2252 #2251 #2250

**Comment by tienlee** [comment]
All identified bugs on https://github.com/eclipse-sw360/sw360/issues/2219 were fixed. I think we can release a new version (18.1)
Several open issues (https://github.com/eclipse-sw360/sw360/issues/2252, https://github.com/eclipse-sw360/sw360/issues/2250) should be considered to fix after that.

**Comment by heliocastro** [comment]
#2252 need to be fixed before 18.1.
I'm not keen to see a 18.1.1 released that soon.
Remember, after 18.1, we will move to 18 branch as maintenance branch and then we start to remove liferay ( hooray ) on main.

**Comment by KoukiHama** [comment]
> https://github.com/eclipse-sw360/sw360/issues/2252 need to be fixed before 18.1.
> I'm not keen to see a 18.1.1 released that soon.

OK, @arunazhakesan 
Do you have a strategy for how to deal with the following about Package Portlet?

**Comment by ag4ums** [comment]
I missed #2252, this should be fixed before the release. @arunazhakesan, @afsahsyeda can you please do a hot fix for this issue

**Comment by tienlee** [comment]
> I missed #2252, this should be fixed before the release. @arunazhakesan, @afsahsyeda can you please do a hot fix for this issue

If you are busy, please assign this issue to me.

**Comment by arunazhakesan** [comment]
The group decided to go for this release 18.1.0-M1. Will hold all new PR merges until then.

cc: @ag4ums  @KoukiHama @heliocastro

**Review by smrutis1 — APPROVED** [review]
Changes looks good

**Pull request merged**
