### PR TITLE
feat(rest): saveUsages in project page

### LINKED ISSUE #2371: Save attachment usages endpoint for project
### Description

Endpoint to save attachment usages for the project.

### PR DESCRIPTION
**Pull request by rudra-superrr**
Issue: Closes #2371

Description: this new endpoint is used to save attachmnetUsages for the project.

How to test:
Pass Map< String, List< String >> in request body.
String can be of 4 types:
- selected : release attachmentUsage that you want to save/check
- deselected : release attachmentUsage that you want to delete/uncheck
- selectedConcludedUsages : release attachmentUsage that you want to save/check of type license info's conclusion checkbox only
- deselectedConcludedUsages:  release attachmentUsage that you want to delete/uncheck of type license info's conclusion checkbox only

Format of String inside list varies according to the usageFields (sourcePackage, licenseInfo, manuallySet) :
- for `sourcePackage`, releaseId_sourcePakage_attachmentContentId
- for `licenseInfo`, projectId-releaseId_licenseInfo_attachmentContentId (for directly linked project) OR projectPath-releaseId_licenseInfo_attachmentContentId (for nested projects)
- for `manuallySet`, releaseId_manuallySet_attachmentContentId

Example:
{"selected": ["4427a8e723ad405db63f75170ef240a2_sourcePackage_5c5d6f54ac6a4b33bcd3c5d3a8fefc43", "value2"],
 "deselected": ["de213309ba0842ac8a7251bf27ea8f36_manuallySet_eec66c3465f64f0292dfc2564215c681", "value2"],
 "selectedConcludedUsages": ["de213309ba0842ac8a7251bf27ea8f36_licenseInfo_eec66c3465f64f0292dfc2564215c681"],"
 "deselectedConcludedUsages":
 ["ade213309ba0842ac8a7251bf27ea8f36_licenseInfo_aeec66c3465f64f0292dfc2564215c681"]}

### CODE REVIEW

**Comment by keerthi-bl** [comment]
Testing this PR.

**Comment by keerthi-bl** [comment]
Test successfull.

PR_2371_SUCCESS_VALIDATION

PR_2371_SUCCESS_FAILURE

**Review by GMishx — APPROVED** [review]
Changes looks good. Please rebase with latest main.

**Comment by GMishx** [comment]
@keerthi-bl please retest the branch after rebase.

**Comment by rudra-superrr** [comment]
Rebase completed, now you can retest this @keerthi-bl .

**Comment by keerthi-bl** [comment]
Test successfull.

image

**Review by GMishx — APPROVED** [review]

**Pull request merged**
