### PR TITLE
Fix(Component UI): Can not load component detail page with long text of additional data

### PR DESCRIPTION
**Pull request by hoangnt2**
Issue: #1772 

### How To Test?
Refer to: #1772 

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Testing was successful.

image

**Comment by rudra-superrr** [comment]
One thing I want to add, maximum length allowed for a word in additional data's value is 29 letters.
If additional data's value exceeds 29 letters for a word then additional data won't be displayed.

In the below ss value for key(keyyy) exceeds 29 letters.
image

image

**Comment by hoangnt2** [comment]
Hi @rudra-superrr.
I want to confirm that **all additional data** or the **additional data with a word exceed 29 letters** won't be displayed?
In your image, all additional data will be hidden.

**Comment by rudra-superrr** [comment]
Yes, all additional data are not getting displayed.

**Comment by hoangnt2** [comment]
Hi @rudra-superrr  
I implemented your idea, please help me to test it.

**Comment by rudra-superrr** [comment]
Hi @hoangnt2 ,
Now nothing is getting displayed under additional data tab.

**Comment by hoangnt2** [comment]
Hi @rudra-superrr,

> One thing I want to add, maximum length allowed for a word in additional data's value is 29 letters. If additional data's value exceeds 29 letters for a word then additional data won't be displayed.
> 
> In the below ss value for key(keyyy) exceeds 29 letters. image
> 
> image

Is it correct with your description?

**Comment by rudra-superrr** [comment]
> Hi @rudra-superrr,
> 
> > One thing I want to add, maximum length allowed for a word in additional data's value is 29 letters. If additional data's value exceeds 29 letters for a word then additional data won't be displayed.
> > In the below ss value for key(keyyy) exceeds 29 letters. image
> > image
> 
> Is it correct with your description?

Yes

**Comment by hoangnt2** [comment]
@rudra-superrr, thanks for your help

**Review by smrutis1 — APPROVED** [review]
Code looks good.

**Comment by rudra-superrr** [comment]
Hi @hoangnt2 ,
Nothing is getting displayed for additional data field.

image

image

**Comment by rudra-superrr** [comment]
@hoangnt2 , you were right.
but still if the value of the key for additional data exceeds 29 letters then no data is displayed.

**Comment by tienlee** [comment]
> but still if the value of the key for additional data exceeds 29 letters then no data is displayed.
@rudra-superrr : I think there is a misunderstanding here.

Hoang asks you (Dec 22) if an additional data (key1,value1) exceeds 29 letters, then
1. (key1,value1) won't be displayed
or
2. all additional data will be hidden. All additional data means that (key1,value1), (key2,value2), ...

You said that (Dec 22): Yes, all additional data are not getting displayed.
So, Hoang has implemented option 2.

But, I think you are expecting option 1. Is that right?

**Comment by rudra-superrr** [comment]
Hi @tienlee ,
The point is if the value of the key exceeds 29 letters, then nothing is getting displayed and this should not be the case, right?
I want all data under additional data to be displayed irrespective of value's length.

**Comment by tienlee** [comment]
> Hi @tienlee , The point is if the value of the key exceeds 29 letters, then nothing is getting displayed and this should not be the case, right? I want all data under additional data to be displayed irrespective of value's length.

Thank you. I understood.
I will discuss with Hoang tomorrow and update this PR soon.

**Comment by hoangnt2** [comment]
@rudra-superrr, i have fixed issue and add the validation for additional data text. When users enter the text with length exceed 29 letters then they focus out or click update button, the error message will be shown as bellow.
image
Please use **Ctrl + F5** in component detail page to refresh cache.

**Comment by rudra-superrr** [comment]
Hi @hoangnt2 ,
This validation won't help as links can contain more than 29 characters.
Just try to remove 29 characters limit from the value field and it will solve the problem.

**Comment by hoangnt2** [comment]
@rudra-superrr, I removed validation and now component detail page can show additional data with text exceed 29 letters
image

**Comment by rudra-superrr** [comment]
Testing was successful.

**Pull request merged**
