### PR TITLE
feat(rest) - Rest API for downloading components report.

### PR DESCRIPTION
**Pull request by keerthi-bl**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
#1855 

> * Did you add or update any new dependencies that are required for your change?

No

Issue: 

### How To Test?
It can be tested using Rest client (Postman) with following URL and sample response.

URL : http://localhost:8080/resource/api/reports?withlinkedreleases=true&mimetype=xlsx&mailrequest=true&module=components

HTTPRequest type : GET

Header (Add Authorisation : Token avbxxxxxxxxxxxh)

Sample response : 

{
    "response": "E-mail sent succesfully to the end user.",
    "url": "http://127.0.0.1:8080/resource/api/reports/download?user=keerthi.bl@sw360.org&module=components&extendedByReleases=true&token=/tmp/keerthi.bl@sw360.org/2023-05-17_a990c489-acf8-4600-911c-2d89015b8bba"
}

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by keerthi-bl** [comment]
This PR can only be merged only after the PR - https://github.com/eclipse-sw360/sw360/pull/1902 get merged.

**Comment by smrutis1** [comment]
Please update the commit message

image

**Comment by nikkuma7** [comment]
Test Successful.

image
image
image
image

**Review by smrutis1 — CHANGES_REQUESTED** [review]
Requesting minor changes

**Comment by keerthi-bl** [comment]
Review comments addressed.

**Review by smrutis1 — APPROVED** [review]
CLGTM

**Pull request merged**
