### PR TITLE
feat(ui) : Feat/collapse icon indicator

### PR DESCRIPTION
**Pull request by sameed20**
Issue: #2052 
Various tabs in portlets are expanded by default but there is no icon to indicate that these tiles are collapsible.

Change:
I have added the expand/collapse icon to all those tabs which can expand/collapse.

ExpandCollapse

### CODE REVIEW

**Comment by sameed20** [comment]
> Hello
> 
> CI　returned the error. Please Change the commit history.
> 
> ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝ Run webiny/action-conventional-commits@v1.1.0 ℹ️ Checking if commit messages are following the Conventional Commits specification... Commit messages: 🚩 (feat):Added collapse and expand icon for all the tabs
> 
> Signed-off-by: sameed.ahmad [sameed.ahmad@siemens-healthineers.com](mailto:sameed.ahmad@siemens-healthineers.com) ✅ Revert "(feat):Added collapse and expand icon for all the tabs"
> 
> This reverts commit [5](https://github.com/eclipse-sw360/sw360/actions/runs/5936176270/job/16096573588?pr=2095#step:3:6)1[6](https://github.com/eclipse-sw360/sw360/actions/runs/5936176270/job/16096573588?pr=2095#step:3:7)3cc1[7](https://github.com/eclipse-sw360/sw360/actions/runs/5936176270/job/16096573588?pr=2095#step:3:8)45b55e10a75d40a2d20ed5f1a5ca1eb2. 🚩 Revert "Revert "(feat):Added collapse and expand icon for all the tabs""
> 
> This reverts commit [60217db](https://github.com/eclipse-sw360/sw360/commit/60217db8f32f9182488031b0940f7988768e9552)[8](https://github.com/eclipse-sw360/sw360/actions/runs/5936176270/job/16096573588?pr=2095#step:3:9)f32f[9](https://github.com/eclipse-sw360/sw360/actions/runs/5936176270/job/16096573588?pr=2095#step:3:10)182488031b0940f7988768e9552. Error: 🚫 According to the conventional-commits specification, some of the commit messages are not valid.

Hi,
I have updated the commit history, you can review.

**Comment by afsahsyeda** [comment]
I have carried out a general test. Please note:

- Replace the existing "click to expand or collapse" text with "Click to Expand" or "Click to Collapse" for each icon respectively.
- This feature is not implemented for the Packages portlet.

**Comment by sameed20** [comment]
> I have carried out a general test. Please note:
> 
> * Replace the existing "click to expand or collapse" text with "Click to Expand" or "Click to Collapse" for each icon respectively.
> * This feature is not implemented for the Packages portlet.



> I have carried out a general test. Please note:
> 
> * Replace the existing "click to expand or collapse" text with "Click to Expand" or "Click to Collapse" for each icon respectively.
> * This feature is not implemented for the Packages portlet.

Hi,
I have made the changes suggested, can you please review.

**Review by afsahsyeda — APPROVED** [review]

**Comment by ag4ums** [comment]
@hoangnt2, can we merge this PR?

**Review by hoangnt2 — APPROVED** [review]

**Comment by hoangnt2** [comment]
@ag4ums We can merge it now

**Pull request merged**
