### PR TITLE
feat(rest): Adding new endpoint to get releases of linked projects.

### LINKED ISSUE #2418: Endpoint for releases of linked projects.
### Description
Endpoint for releases of linked project for a project.

image

### PR DESCRIPTION
**Pull request by rudra-superrr**
Issue: Closes #2418 

Test:
Run the endpoint to get the releases of the linked projects for a project.
http://localhost:8080/resource/api/projects/71057adec8094a98baf7c16524ea1f62/linkedProjects/releases

### CODE REVIEW

**Comment by keerthi-bl** [comment]
Testing this PR

**Comment by keerthi-bl** [comment]
Tested and observed following points.

1. Pagination may required. 

2. Please add proper message in the response 

image

3. Rename PR and Issue title. For example : Adding/Creating new endpoint to get releases of linked projects.

**Comment by rudra-superrr** [comment]
Hi @keerthi-bl, made the required changes.

**Comment by keerthi-bl** [comment]
Test Completed. Working as expected.

image

**Comment by GMishx** [comment]
@rudra-superrr please rebase with latest main.

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Pull request merged**
