### PR TITLE
fix(mod): show message when only moderator choose remove me option

### LINKED ISSUE #2228: Missed warning message when the only moderator chooses the "Remove Me from Moderators" option
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

In version 18.0, there is no warning message when the moderator tries to remove himself from the moderation request. 

#### How to reproduce

- Pre-condition
  - User1 creates a moderation request (MR1).
  - Only User2 has the authority to approve this request.
- Procedure
  - Log-in SW360 with User2.
  - Go to moderation request MR1
  - Click on "Remove Me from Moderators" button.
- Expected: The warning message "You are the last moderator for this request - you are not allowed to unsubscribe." will be displayed.
- Actual: There is no warning message displayed. User2 was not removed from moderators.

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

### PR DESCRIPTION
**Pull request by rudra-superrr**
Issue: Closes #2228

Description: message "You are the last moderator for this request - you are not allowed to unsubscribe." will be displayed when last moderator try to remove himself from moderator list.

### CODE REVIEW

**Comment by KoukiHama** [comment]
Could you check and review PR?
@hoangnt2 @tienlee

**Comment by KoukiHama** [comment]
Note : Version 18.1 can be released when this is merged
@ag4ums

**Review by hoangnt2 — COMMENTED** [review]
Change look good

**Comment by KoukiHama** [comment]
Fixing my own notes.

The following will need to be merged before the 18.1 release.However, we will be able to release 18.1 by Christmas.

https://github.com/eclipse-sw360/sw360/pull/2235

**Review by ag4ums — APPROVED** [review]
working as expected

**Pull request merged**
