### PR TITLE
fix(liferay) Fix liferay "unable to load filter" issue

### PR DESCRIPTION
**Pull request by ljaenicke**
When loading liferay, the ERROR
  unable to load filter com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter
is logged.
The fix found in
https://liferay.dev/ask/questions/development/vaadin-portlet-bundle-is-unable-to-load-filter-1
is working.

Signed-off-by: Lutz Jaenicke <ljaenicke@phoenixcontact.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue:  #1810

### How To Test?
Review log files without/with the fix

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Review by KoukiHama — APPROVED** [review]

**Comment by KoukiHama** [comment]
codes are ok.

**Comment by akapti** [comment]
Tested in my locl and getting following error after starting the tomcat.
```
2023-01-19 01:26:11.045 INFO  [Start Level: Equinox Container: ca6ea814-4eef-4360-89dd-2ac7c03108c2][DynamicComponentManager:59] Enable component [org.eclipse.sw360.portal.portlets.projectimport.BdpImportPortlet]
2023-01-19 01:26:11.052 INFO  [Start Level: Equinox Container: ca6ea814-4eef-4360-89dd-2ac7c03108c2][DynamicComponentManager:59] Enable component [org.eclipse.sw360.portal.portlets.projectimport.WsImportPortlet]
2023-01-19 01:26:11.110 ERROR [Framework Event Dispatcher: Equinox Container: ca6ea814-4eef-4360-89dd-2ac7c03108c2][Framework:93] FrameworkEvent ERROR 
com.liferay.portal.kernel.log.LogSanitizerException: org.osgi.framework.BundleException: Could not resolve module: org.eclipse.sw360.liferay-theme [2336]_  Unresolved requirement: Import-Package: android.os; resolution:="optional"_  Unresolved requirement: Import-Package: android.util; resolution:="optional"_  Unresolved requirement: Import-Package: com.conversantmedia.util.concurrent; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.jackson.dataformat.xml; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.jackson.dataformat.xml.annotation; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.jackson.dataformat.xml.util; resolution:="optional"_  Unresolved requirement: Import-Package: com.fasterxml.jackson.dataformat.yaml; resolution:="optional"_  Unresolved requirement: Import-Package: com.github.luben.zstd; resolution:="optional"_  Unresolved requirement: Import-Package: com.google.appengine.api; resolution:="optional"_  Unresolved requirement: Import-Package: com.google.appengine.api.utils; resolution:="optional"_  Unresolved requirement: Import-Package: com.google.apphosting.api; resolution:="optional"_  Unresolved requirement: Import-Package: com.lmax.disruptor; resolution:="optional"_  Unresolved requirement: Import-Package: com.lmax.disruptor.dsl; resolution:="optional"_  Unresolved requirement: Import-Package: com.microsoft.schemas.office.powerpoint; resolution:="optional"_  Unresolved requirement: Import-Package: com.microsoft.schemas.office.word; resolution:="optional"_  Unresolved requirement: Import-Package: javax.jms; resolution:="optional"_  Unresolved requirement: Import-Package: net.sf.ehcache; resolution:="optional"_  Unresolved requirement: Import-Package: net.sf.saxon; resolution:="optional"_  Unresolved requirement: Import-Package: net.sf.saxon.dom; resolution:="optional"_  Unresolved requirement: Import-Package: net.sf.saxon.om; resolution:="optional"_  Unresolved requirement: Import-Package: net.sf.saxon.query; resolution:="optional"_  Unresolved requirement: Import-Package: net.sf.saxon.sxpath; resolution:="optional"_  Unresolved requirement: Import-Package: net.sf.saxon.value; resolution:="optional"_  Unresolved requirement: Import-Package: net.spy.memcached; resolution:="optional"_  Unresolved requirement: Import-Package: okhttp3; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.avalon.framework.logger; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.batik.anim.dom; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.batik.bridge; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.batik.ext.awt; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.batik.ext.awt.image.renderable; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.batik.gvt; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.batik.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.jcp.xml.dsig.internal.dom; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.kafka.clients.producer; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.log; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.logging.log4j.util.internal; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.poi.extractor.ole2; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tools.ant; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tools.ant.taskdefs; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.tools.ant.types; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.xml.resolver; resolution:="optional"_  Unresolved requirement: Import-Package: org.apache.xml.resolver.tools; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1.cmp; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1.nist; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1.ocsp; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1.x500; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.asn1.x509; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.cert; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.cert.jcajce; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.cert.ocsp; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.cms; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.cms.bc; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.operator; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.operator.bc; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.tsp; resolution:="optional"_  Unresolved requirement: Import-Package: org.bouncycastle.util; resolution:="optional"_  Unresolved requirement: Import-Package: org.brotli.dec; resolution:="optional"_  Unresolved requirement: Import-Package: org.etsi.uri.x01903.v14; resolution:="optional"_  Unresolved requirement: Import-Package: org.fusesource.jansi; resolution:="optional"_  Unresolved requirement: Import-Package: org.jctools.queues; resolution:="optional"_  Unresolved requirement: Import-Package: org.openxmlformats.schemas.officeDocument.x2006.math; resolution:="optional"_  Unresolved requirement: Import-Package: org.openxmlformats.schemas.schemaLibrary.x2006.main; resolution:="optional"_  Unresolved requirement: Import-Package: org.slf4j.ext; resolution:="optional"_  Unresolved requirement: Import-Package: org.tukaani.xz; resolution:="optional"_  Unresolved requirement: Import-Package: org.zeromq; resolution:="optional"_  Unresolved requirement: Import-Package: sun.nio.ch; resolution:="optional"_  Unresolved requirement: Import-Package: com.liferay.portal.servlet.filters.invoker_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1682) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1662) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1624) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1555) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) ~[org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi.jar:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [org.eclipse.osgi.jar:?]
2023-01-19 01:26:11.215 INFO  [main][BuildInfoTemplateContextContributor:33] Component [org.eclipse.sw360.portal.components.BuildInfoTemplateContextContributor] has been DISABLED.
2023-01-19 01:26:11.216 INFO  [main][DynamicComponentManager:80] Disable component [org.eclipse.sw360.portal.users.LoginAction]
2023-01-19 01:26:11.230 INFO  [main][DynamicComponentManager:80] Disable component [org.eclipse.sw360.portal.users.SSOAutoLogin]
2023-01-19 01:26:11.239 INFO  [main][DynamicComponentManager:80] Disable component [org.eclipse.sw360.portal.components.BuildInfoTemplateContextContributor]
```
It would be really helpful if anybody else test this change?

**Comment by ljaenicke** [comment]
I can see this on another test setup as well. It will be a few days before I can get back to my other system to see whether I just did not notice this effect...

**Comment by ljaenicke** [comment]
Note: I am not familiar with liferay and this setup, so I just "believed" the fix in the mentioned post. If anybody has a better solution...

**Comment by ag4ums** [comment]
@ljaenicke  are you looking into it....

**Comment by ljaenicke** [comment]
I have put some more work into it in the meantime.

Using the fix I found in another context does remove the ERROR message, however at the price of the message(s) mentioned by @akapti . It is my understanding that these messages are warnings only, as the modules are flagged as optional and no more error message can be observed and no other problem could be observed. At least I could not find one.

I have checked that the InvokerFilter class is availble in the portal.kernel archive as downloaded during the build process. I have tried additionally to modify "frontend/sw360-portlet/bnd.bnd" with respective Import-Package and/or Export-Package statements concerning the classes, but all without improvements on the overall situation.

I do not understand the details leading to this effect, I am not familiar with liferay which comes with its own set of  libraries and OSGI. The code surrounding this issue does not seem to be too complex, however it also seems not too easy to just built from scratch and use some plain old debugging techniques.

So: I am giving up...

**Comment by heliocastro** [comment]
Since we are moving on from Liferay, I will close this one. Please feel free to reopen if became relevant for backward versions.

**Pull request closed without merging**
