### PR TITLE
fix(servlet): complete migration javax to jakarta

### PR DESCRIPTION
**Pull request by GMishx**
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

Replace all `javax.*` dependencies with `jakarta.*` dependencies as Tomcat 11 completes the migration and servlets refuse to load.

Did not migrate to latest jakarta-mail `2.1.3` as it throws error "No provider of jakarta.mail.util.StreamProvider was found". `2.0.1` is the latest version which works.

Also, fix some compile warnings from Java 11.

### Suggest Reviewer
@heliocastro

### How To Test?
Setup new backend with Java 21+ and Apache Tomcat 11.

### CODE REVIEW

**Review by heliocastro — APPROVED** [review]
Looks good to me

**Comment by heliocastro** [comment]
@GMishx Something gone wrong

**Comment by GMishx** [comment]
@heliocastro , should be good now :-)

**Review by heliocastro — APPROVED** [review]
LGTM
It's quite a good surprise that we have really few vulnerabilities now, due all the changes. Progress was huge

**Pull request merged**
