### PR TITLE
fix(UI): Moderation Request for releases does not show any changes issue fix

### LINKED ISSUE #2368: Moderation Request does not show any changes - Releases
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description
Steps :

1. Create a moderation request of any release
2. next time onwards keep submit to create a moderation request of the same without any changes
3. It will keep create the moderation request in old code

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

### PR DESCRIPTION
**Pull request by keerthi-bl**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: 

Closes #2368 

### How To Test?
Steps : 

1. Create a moderation request of any release
2. next time onwards keep submit to create a moderation request of the same without any changes
3. It will keep create the moderation request in old code
4. This issue is fixed with this Validation PR
5. It should not allow if no changes made while creating a moderation request of any release.

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by nikkuma7** [comment]
I followed the above test steps, but MR is creating.

**Comment by GMishx** [comment]
@keerthi-bl this PR can be closed as the changes are in only in frontend which does not exist anymore?

**Comment by keerthi-bl** [comment]
Yes @GMishx . We can close this issue and PR here. We may also need to open this issue in new UI repo as well.

**Comment by GMishx** [comment]
Can you please open the issue in https://github.com/eclipse-sw360/sw360-frontend/ for the same and then close this PR @keerthi-bl then?

**Comment by keerthi-bl** [comment]
Closing this PR, issue has been created at the front-end for the same with ref : https://github.com/eclipse-sw360/sw360-frontend/issues/310

FYR : @GMishx :

**Pull request closed without merging**
