### PR TITLE
fix(rest): url decoding.

### LINKED ISSUE #2330: Url Encoded Component names are not searchable
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description
Related Issues, Pull Requests:

https://github.com/eclipse-sw360/sw360/issues/2115
https://github.com/eclipse-sw360/sw360/pull/2043
https://github.com/eclipse-sw360/sw360/issues/2042

Came across an issue with components containig "/" in the name which now cannot be searched. Same will be true for other special chars

Seems the mentioned merge request ( https://github.com/eclipse-sw360/sw360/pull/2043 ) allows searching without encoding but now breaks encoded search strings due to the poor parsing of the query string. There is possibly a better solution to support unencoded parameters. 

The new "parseQueryString" method looks very unsafe and could possibly break in many possible ways and also could also be a security risk ?

The "official" SW360 client implementation  DOES urlencode  the parameters and is now broken for package names with special chars. 

#### How to reproduce

Use OSS Review toolkit and use the "upload-result-to-sw360" goal which uses the sw360 client library https://central.sonatype.com/artifact/org.eclipse.sw360/client
https://oss-review-toolkit.org/ort/docs/guides/sw360-integration
This breaks when components already exist on SW360

Another code snippet to test this:
Result: An empty array is printed
Expected: Details of the "org.apache.logging.log4j/log4j-core" should be printed
```
		SW360ConnectionFactory factory = new SW360ConnectionFactory();
		SW360Connection c = factory.newConnection(config);
		ComponentSearchParams searchParams = ComponentSearchParams.builder()
		        .withName("org.apache.logging.log4j/log4j-core")
		        .build();
		System.out.println(c.getComponentAdapter().search(searchParams));

```

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

### PR DESCRIPTION
**Pull request by rudra-superrr**
Issue: closes #2330 

Description: decoding the query parameters for rest endpoints.

How to test:
- send the query parameters in encoded format for rest endpoints.

Test endpoints like:
- search components/projects/releases by name
- search components/projects/releases by externalIds
- search projects by tag

Screenshots:
image

image

### CODE REVIEW

**Comment by afsahsyeda** [comment]
@akshitjoshii please perform the test.

**Comment by akshitjoshii** [comment]
Testing successful for the following endpoints :
-  search components/projects/releases by **name**
- search components/projects/releases by **externalIds**
- search projects by **tag**
comp_name

**Comment by akshitjoshii** [comment]
An endpoint where url encoding can be added is **search packages** by **name**.
image

**Comment by rudra-superrr** [comment]
> An endpoint where url encoding can be added is **search packages** by **name**. image

Made the changes. Added url decoding for this endpoint too.

**Comment by Sekagra** [comment]
Note from a SW360 API user: 
Please consider using a built-in functionality from Spring like [UriComponentBuilder.fromUriString](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/UriComponentsBuilder.html#fromUriString(java.lang.String)) instead of the manual parsing implemented in your `RestControllerHelper.parseQueryString()` method.

**Comment by rudra-superrr** [comment]
> Note from a SW360 API user: Please consider using a built-in functionality from Spring like [UriComponentBuilder.fromUriString](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/UriComponentsBuilder.html#fromUriString(java.lang.String)) instead of the manual parsing implemented in your `RestControllerHelper.parseQueryString()` method.

Thanks for the suggestion.

**Review by heliocastro — CHANGES_REQUESTED** [review]
Please accept the suggestion on the thread and use a well formed Url parsing library instead of own solutions

**Comment by rudra-superrr** [comment]
> Please accept the suggestion on the thread and use a well formed Url parsing library instead of own solutions

Hi @heliocastro , already implemented the suggestion in the code.

**Review by heliocastro — APPROVED** [review]
Ok, Good to Go

**Comment by heliocastro** [comment]
> > Please accept the suggestion on the thread and use a well formed Url parsing library instead of own solutions
> 
> Hi @heliocastro , already implemented the suggestion in the code.

Maybe we should have this as a suggestion in the developer documentations, like a FAQ on what to use in such cases. 
@Sekagra  Can you create a discussion over Improve Developer Guidelines for SW360 ?

**Comment by akshitjoshii** [comment]
testing was successful all endpoints working as expected.
new_test

**Pull request merged**
