### PR TITLE
fix(licenses): Update Response for api single license and add rest api docs create License

### PR DESCRIPTION
**Pull request by tuannn2**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### feature: 
- Update response for API single License
- Add rest docs for API Create License

### How To Test?

- Run command line: 
```
$ curl 'https://sw360.org/api/licenses/Apache-2.0' -i -X GET \
    -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsic3czNjAtUkVTVC1BUEkiXSwidXNlcl9uYW1lIjoiYWRtaW5Ac3czNjAub3JnIiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY5ODgyODgyNCwiYXV0aG9yaXRpZXMiOlsiUkVBRCIsIldSSVRFIl0sImp0aSI6Inh4Z1RBZ2pIcUFfZkpuS3EwVmkxQXVFS0ZIZyIsImNsaWVudF9pZCI6InRydXN0ZWQtc3czNjAtY2xpZW50In0.e6mw__gXV5fsQ4GkcG-RIlKjywvkbczCmG7czqTU6j5w5fHgreUtXOTjwl0hdDudpPLR--hNP2TZgGL-abPz2cYO2xj3LHd3uQcBeOwcfawo7MxcZY8T0xIzbqhqtkNusMXc8bEGf9B5OHiGSLEvDVE8E1J7ItyYyoVEnezW-d9ODJ9EVzAqpPTPS2ipqUfSZKDWTSOg8srJAE6Qy2Ig7JPYQK6MzAPbK5YbkAhbvR5KHY3e3s-ZW_1HTO3iftnMqvtDIj7VrGfFFsaSE8R2KiVv04AauL9ePh7dRj6m_KxtryygEv9GnKSwtoUrbimDP-zCU_QPHmV9mn0WevQWDw' \
    -H 'Accept: application/hal+json'

```

- Response:

```
{
  "externalLicenseLink" : "https://spdx.org/licenses/Apache-2.0.html",
  "note" : "License's Note",
  "externalIds" : {
    "Trove" : "License :: OSI Approved :: Apache Software License",
    "SPDX" : "Apache-2.0"
  },
  "additionalData" : {
    "Key" : "Value"
  },
  "OSIApproved" : "NA",
  "FSFLibre" : "NA",
  "obligations" : [ {
    "type" : "obligation",
    "text" : "This is text of Obligation 1",
    "title" : "Obligation 1",
    "obligationLevel" : "LICENSE_OBLIGATION",
    "obligationType" : "PERMISSION"
  }, {
    "type" : "obligation",
    "text" : "This is text of Obligation 2",
    "title" : "Obligation 2",
    "obligationLevel" : "LICENSE_OBLIGATION",
    "obligationType" : "OBLIGATION"
  } ],
  "obligationDatabaseIds" : [ "0002", "0001" ],
  "text" : "placeholder for the Apache 2.0 license text",
  "checked" : true,
  "shortName" : "Apache 2.0",
  "fullName" : "Apache License 2.0",
  "_links" : {
    "self" : {
      "href" : "https://sw360.org/api/licenses/Apache-2.0"
    }
  },
  "_embedded" : {
    "sw360:obligations" : [ {
      "text" : "This is text of Obligation 1",
      "title" : "Obligation 1",
      "obligationType" : "PERMISSION",
      "_links" : {
        "self" : {
          "href" : "https://sw360.org/api/obligations/0001"
        }
      }
    }, {
      "text" : "This is text of Obligation 2",
      "title" : "Obligation 2",
      "obligationType" : "OBLIGATION",
      "_links" : {
        "self" : {
          "href" : "https://sw360.org/api/obligations/0002"
        }
      }
    } ]
  }
}

```

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by nikkuma7** [comment]
Test successful.

image

**Comment by rudra-superrr** [comment]
Hi @tuannn2 , as I can see obligations data is coming twice in your response structure, any specific reason for this?
My suggestion would be to add "type" and "obligationLevel" to the embedded structure of obligations and remove the obligations field from response in order to prevent redundancy OR just remove the embedded structure of obligations..

**Comment by tuannn2** [comment]
> Hi @tuannn2 , as I can see obligations data is coming twice in your response structure, any specific reason for this? My suggestion would be to add "type" and "obligationLevel" to the embedded structure of obligations and remove the obligations field from response in order to prevent redundancy OR just remove the embedded structure of obligations..

Thank you for your comment, @rudra-superrr.
Because, I need id of obligation, so I removed the obligations field from response.

**Comment by rudra-superrr** [comment]
Code looks good.

**Pull request merged**
