### PR TITLE
feat(api): new endpoint /mySubmissions

### LINKED ISSUE #1849: REST API for Moderation request
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Create new REST endpoint for moderation requests.

#### Steps followed and expected result

Part of #1826

### PR DESCRIPTION
**Pull request by GMishx**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

New endpoint `/moderationrequest/mySubmissions` to get moderation requests submitted by the user.

Also, refactor the `ModerationRequestController` to use `ModerationRequestController.getModerationResponseEntity()`

Closes #1849

Issue: #1849

### How To Test?
1. Check the docs for the new endpoint.
2. Check moderation request matches the "My Task Submissions" list from SW360 Homepage.

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Testing was successful.

image
image

**Comment by rudra-superrr** [comment]
Can you add one more parameter i.e. sort, so that mySubmissions can be sorted on the basis of status and document name.

**Comment by GMishx** [comment]
@rudra-superrr , I've added the comparators so the sorting should work. Have also documented the sort parameter for OpenAPI and spring doc. Please check.

**Comment by rudra-superrr** [comment]
Looks good to me.

**Pull request merged**
