### PR TITLE
feat(UI): Add an info button in the create CR page

### PR DESCRIPTION
**Pull request by akshitjoshii**
[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

Add an i button below the preferred clearing date field in the create CR page and update the comments field text.
Closes: #2281 
Screenshot from 2024-01-23 13-38-44

### CODE REVIEW

**Comment by rudra-superrr** [comment]
Information not getting shown when hovering on info button.
image

**Comment by akshitjoshii** [comment]
Hi @rudra-superrr pls check now.
Screenshot from 2024-01-30 15-11-37

**Comment by arunazhakesan** [comment]
@rudra-superrr please review and add `ready` label if its complete.

**Comment by rudra-superrr** [comment]
Code looks good to me.

**Pull request merged**
