### PR TITLE
feat(UI): enhanced date filter for open and closed clearing requests tab

### PR DESCRIPTION
**Pull request by sameed20**
pr1

pr2

Closes: #2264

### CODE REVIEW

**Comment by akshitjoshii** [comment]
I am testing this PR.

**Comment by akshitjoshii** [comment]
the date filter in moderation request tabs is not working when the date is selected. Please check.
Screenshot from 2024-02-01 11-10-24

**Comment by sameed20** [comment]
Hi @akshitjoshii I have pushed the changes. Can you please test it again.

**Comment by akshitjoshii** [comment]
Hi @sameed20, the open CR page and closed CR page is not listing the CRs on fresh loading. Some filter is being applied on default. Pls check.
Screenshot from 2024-02-05 12-02-50

**Comment by akshitjoshii** [comment]
testing was successful.
Screenshot from 2024-02-08 18-45-41

**Comment by rudra-superrr** [comment]
Code looks good.

**Pull request merged**
