### PR TITLE
fix(rest): Resolved null value returning for svm tracking status.

### PR DESCRIPTION
**Pull request by akshitjoshii**
closes : #2617 

**Endpoint** : http://localhost:8080/resource/api/vulnerabilities/trackingStatus/{projectId}

image

### CODE REVIEW

**Comment by rudra-superrr** [comment]
LGTM

**Comment by sameed20** [comment]
Test successful.

**Comment by GMishx** [comment]
Tested, working as expected.

**Review by GMishx — APPROVED** [review]
Tested, working as expected.

**Pull request merged**
